# Generated by Django 3.0.8 on 2020-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_marks',
            field=models.IntegerField(default=10),
        ),
    ]
